name: zola check

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            submodules: recursive
        - uses: taiki-e/install-action@v2
          with:
            tool: zola@0.19.2
        - name: Check internal
          run: zola check --skip-external-links
        - name: Check external (warning only)
          run: zola check || exit 78
