name: Deploy Zola Site via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Zola
      run: |
        curl -L https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz -o zola.tar.gz
        tar -xzf zola.tar.gz
        sudo mv zola /usr/local/bin/

    - name: Build the Zola site
      run: zola build

    - name: Deploy via SFTP
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets.FTP_DOMAIN }}
        port: ${{ secrets.FTP_PORT }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        uploads: |
            ./public/ => .
        delete: 'true'
